### ISSUE TITLE
Failed to handle method call

### ISSUE THREAD

**Issue by JAICHANGPARK** [mintware-de/flutter_p2p#11]
Failed to handle method call
E/MethodChannel#de.mintware.flutter_p2p/flutter_p2p(13511): java.lang.IllegalArgumentException: Unsupported value: java.lang.reflect.InvocationTargetException
E/MethodChannel#de.mintware.flutter_p2p/flutter_p2p(13511): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:278)
E/MethodChannel#de.mintware.flutter_p2p/flutter_p2p(13511): 	at io.flutter.plugin.common.StandardMethodCodec.encodeErrorEnvelope(StandardMethodCodec.java:69)
E/MethodChannel#de.mintware.flutter_p2p/flutter_p2p(13511): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:236)
E/MethodChannel#de.mintware.flutter_p2p/flutter_p2p(13511): 	at de.mintware.flutter_p2p.FlutterP2pPlugin.onMethodCall(FlutterP2pPlugin.kt:352)
E/MethodChannel#de.mintware.flutter_p2p/flutter_p2p(13511): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:226)
E/MethodChannel#de.mintware.flutter_p2p/flutter_p2p(13511): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#de.mintware.flutter_p2p/flutter_p2p(13511): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:631)
E/MethodChannel#de.mintware.flutter_p2p/flutter_p2p(13511): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#de.mintware.flutter_p2p/flutter_p2p(13511): 	at android.os.MessageQueue.next(MessageQueue.java:325)
E/MethodChannel#de.mintware.flutter_p2p/flutter_p2p(13511): 	at android.os.Looper.loop(Looper.java:142)
E/MethodChannel#de.mintware.flutter_p2p/flutter_p2p(13511): 	at android.app.ActivityThread.main(ActivityThread.java:6528)
E/MethodChannel#de.mintware.flutter_p2p/flutter_p2p(13511): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#de.mintware.flutter_p2p/flutter_p2p(13511): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
E/MethodChannel#de.mintware.flutter_p2p/flutter_p2p(13511): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by devtronic** [comment]
I'll fix this today.
