### ISSUE TITLE
Gradle Plugin version(Kotlin version) issue

### ISSUE THREAD

**Issue by devanshhooda** [mintware-de/flutter_p2p#14]
![image](https://user-images.githubusercontent.com/43931542/84499794-e7c76180-acd0-11ea-81b4-950230d2eb5d.png)

**Comment by devtronic** [comment]
Please use the Bug Report template.

**Comment by devtronic** [comment]
Please provide a minimal example to reproduce the problem.

**Comment by devanshhooda** [comment]
> Please provide a minimal example to reproduce the problem.

This problem is occurring on running the example code provided in the repository.

**Comment by devanshhooda** [comment]
**Solution:** It does not work with the android gradle plugin version 3.3.1 (or higher) so you need to downgrade the plugin version to **3.2.1** to make it run properly.
